-- 코드를 입력하세요
SELECT A.CAR_ID
     , A.CAR_TYPE
     , (A.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(B.DISCOUNT_RATE, '%'))) / 100) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
      ON A.CAR_TYPE = B.CAR_TYPE
      AND B.DURATION_TYPE = '30일 이상'
    LEFT OUTER JOIN (
        SELECT C.CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
            INNER JOIN CAR_RENTAL_COMPANY_CAR D
              ON C.CAR_ID = D.CAR_ID
          WHERE TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221130'
            AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101' 
          GROUP BY C.CAR_ID
    ) E
      ON A.CAR_ID = E.CAR_ID
  WHERE E.CAR_ID IS NULL
    AND (A.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(B.DISCOUNT_RATE, '%'))) / 100) >= 500000
    AND (A.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(B.DISCOUNT_RATE, '%'))) / 100) < 2000000
  ORDER BY (A.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(B.DISCOUNT_RATE, '%'))) / 100) DESC
         , A.CAR_TYPE
         , A.CAR_ID DESC
         ;