-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P
INNER JOIN (SELECT APNT_NO, PT_NO, MDDR_ID, MCDP_CD, APNT_YMD
            FROM APPOINTMENT
            WHERE MCDP_CD = 'CS'
            AND APNT_CNCL_YN = 'N'
            AND APNT_YMD >= TO_DATE('2022-04-13', 'YYYY-MM-DD')
            AND APNT_YMD < TO_DATE('2022-04-14', 'YYYY-MM-DD')) A
ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD;
