-- 코드를 입력하세요
SELECT *
FROM (SELECT F.FLAVOR
    FROM FIRST_HALF F 
    INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
                      FROM JULY
                      GROUP BY FLAVOR) J
    ON F.FLAVOR = J.FLAVOR
    GROUP BY F.FLAVOR
    ORDER BY (SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER)) DESC)
WHERE ROWNUM <= 3;