-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE)AS TOTAL_SALES
FROM BOOK B, AUTHOR A, (SELECT S.BOOK_ID, SUM(S.SALES) AS SALES
           FROM BOOK_SALES S
           WHERE S.SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
           AND S.SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
           GROUP BY BOOK_ID) S
WHERE B.BOOK_ID = S.BOOK_ID
AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC 