-- 코드를 입력하세요
SELECT NVL(H.HOUR, 0) AS HOUR, COUNT(A.HOUR)
FROM (SELECT LEVEL -1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24) H
LEFT OUTER JOIN (SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR
           FROM ANIMAL_OUTS) A
ON H.HOUR = A.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR

