SELECT EXTRACT(YEAR FROM A.SALES_DATE) AS YEAR
     , EXTRACT(MONTH FROM A.SALES_DATE) AS MONTH
     , COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT B.USER_ID)
            / (SELECT COUNT(*)
                FROM USER_INFO
                WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
              ), 1) AS PUCHASED_RATIO
  FROM ONLINE_SALE A
    INNER JOIN USER_INFO B
      ON A.USER_ID = B.USER_ID
  WHERE TO_CHAR(B.JOINED, 'YYYY') = '2021'
  GROUP BY  EXTRACT(YEAR FROM A.SALES_DATE) 
          , EXTRACT(MONTH FROM A.SALES_DATE)
  ORDER BY EXTRACT(YEAR FROM A.SALES_DATE) 
          , EXTRACT(MONTH FROM A.SALES_DATE)