-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,  ROUND(S.SCORE, 2) AS SCORE
FROM (SELECT REST_ID, ROUND((AVG(REVIEW_SCORE)), 3) AS SCORE
     FROM REST_REVIEW
     GROUP BY REST_ID
     ) S
INNER JOIN REST_INFO I
ON S.REST_ID = I.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY S.SCORE DESC, I.FAVORITES DESC
