-- 코드를 입력하세요
select AO.ANIMAL_ID
     , AO.NAME
  from ANIMAL_OUTS AO
  LEFT OUTER JOIN ANIMAL_INS AI
    ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID
     , AO.NAME
     ;