-- 코드를 입력하세요
WITH REVIEW_CNT AS (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(*) = (
            SELECT MAX(CNT)
            FROM (
                SELECT COUNT(*) AS CNT
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
            ) 
        )
)
        
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
JOIN REVIEW_CNT C
ON M.MEMBER_ID = C.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT