-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', USED_GOODS_FILE.BOARD_ID,'/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD
INNER JOIN USED_GOODS_FILE
ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_FILE.BOARD_ID
WHERE USED_GOODS_BOARD.BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
ORDER BY USED_GOODS_FILE.FILE_ID DESC