SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN (SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD')
     AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
     GROUP BY CAR_ID
     HAVING COUNT(*) >= 5) T
ON C.CAR_ID = T.CAR_ID
WHERE C.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD')
     AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
GROUP BY C.CAR_ID, EXTRACT(MONTH FROM START_DATE)
ORDER BY MONTH, C.CAR_ID DESC