
SELECT *
FROM (SELECT I.NAME, I.DATETIME
        FROM ANIMAL_INS I
        LEFT JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
        WHERE O.ANIMAL_ID IS NULL
        ORDER BY DATETIME) A
WHERE ROWNUM <= 3